[package]
edition = "2021"

name = "vsmtp-rule-engine"
version = "1.3.0-rc.1"
license = "GPL-3.0-only"

rust-version = "1.60"

authors = ["Team viridIT <https://viridit.com/>"]
description = "Next-gen MTA. Secured, Faster and Greener"

homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"
documentation = "https://docs.rs/crate/vsmtp-rule-engine/"

readme = "../../../README.md"
keywords = [
  "vsmtp",
  "scripting-engine",
  "scripting-language",
  "scripting",
  "rhai",
]
categories = ["config"]

[package.metadata.release]
pre-release-replacements = [
  { file = "Cargo.toml", search = "vsmtp-common = \\{ path = \"../vsmtp-common\", version = .*", replace = "vsmtp-common = { path = \"../vsmtp-common\", version = \"{{version}}\" }", prerelease = true },
  { file = "Cargo.toml", search = "vsmtp-config = \\{ path = \"../vsmtp-config\", version = .*", replace = "vsmtp-config = { path = \"../vsmtp-config\", version = \"{{version}}\" }", prerelease = true },
  { file = "Cargo.toml", search = "vsmtp-mail-parser = \\{ path = \"../vsmtp-mail-parser\", version = .*", replace = "vsmtp-mail-parser = { path = \"../vsmtp-mail-parser\", version = \"{{version}}\" }", prerelease = true },
  { file = "Cargo.toml", search = "vsmtp-auth = \\{ path = \"../vsmtp-auth\", version = .*", replace = "vsmtp-auth = { path = \"../vsmtp-auth\", version = \"{{version}}\" }", prerelease = true },
]

[dependencies]
vsmtp-common = { path = "../vsmtp-common", version = "1.3.0-rc.1" }
vsmtp-config = { path = "../vsmtp-config", version = "1.3.0-rc.1" }
vsmtp-mail-parser = { path = "../vsmtp-mail-parser", version = "1.3.0-rc.1" }
vsmtp-auth = { path = "../vsmtp-auth", version = "1.3.0-rc.1" }

tracing = "0.1.36"

thiserror = "1.0.32"
# objects
regex = "1.6.0"
iprange = "0.6.7"
ipnet = "2.5.0"
addr = { version = "0.15.4" }

r2d2 = "0.8.10"
csv = "1.1"

mysql = { version = "22.2.0", optional = true, default-features = false, features = [
  "rustls-tls",
  "buffer-pool",
] }
flate2 = { version = "1.0.24", optional = true, default-features = false, features = [
  "zlib",
] }
mysql_common = { version = "0.29.1", optional = true, default-features = false, features = [
  "bigdecimal03",
  "rust_decimal",
  "time03",
  "uuid",
  "frunk",
] }

rhai = { version = "1.9.1", features = [
  "unchecked",
  "sync",
  "internals",
  "no_closure",
] }

strum = { version = "0.24.1", features = ["derive"] }

wait-timeout = "0.2.0"

hostname = "0.3.1"
time = { version = "0.3.14", default-features = false, features = [
  "std",
  "formatting",
  "macros",
] }

trust-dns-resolver = "0.21.2"

[package.metadata.cargo-udeps.ignore]
normal = ["r2d2"]

[dev-dependencies]
vsmtp-mail-parser = { path = "../vsmtp-mail-parser" }
vsmtp-test = { path = "../vsmtp-test" }

[features]
mysql = ["dep:mysql", "dep:flate2", "dep:mysql_common"]
