[package]
edition = "2021"

name = "vsmtp-delivery"
version = "1.3.0-rc.1"
license = "GPL-3.0-only"

rust-version = "1.60"

authors = ["Team viridIT <https://viridit.com/>"]
description = "Next-gen MTA. Secured, Faster and Greener"

homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"
documentation = "https://docs.rs/crate/vsmtp-delivery/"

readme = "../../../README.md"
keywords = ["vsmtp"]
categories = ["network-programming"]

[package.metadata.release]
pre-release-replacements = [
  { file = "Cargo.toml", search = "vsmtp-common = \\{ path = \"../vsmtp-common\", version = .*", replace = "vsmtp-common = { path = \"../vsmtp-common\", version = \"{{version}}\" }", prerelease = true },
  { file = "Cargo.toml", search = "vsmtp-config = \\{ path = \"../vsmtp-config\", version = .*", replace = "vsmtp-config = { path = \"../vsmtp-config\", version = \"{{version}}\" }", prerelease = true },
]

[dependencies]
vsmtp-common = { path = "../vsmtp-common", version = "1.3.0-rc.1" }
vsmtp-config = { path = "../vsmtp-config", version = "1.3.0-rc.1" }

async-trait = "0.1.57"

tracing = "0.1.36"

time = { version = "0.3.14", default-features = false, features = [
  "std",
  "formatting",
  "macros",
] }

users = { version = "0.11.0", features = [] }
trust-dns-resolver = { version = "0.21.2", features = [
  "dns-over-rustls",
  "dnssec-ring",
] }

[dev-dependencies]
