[package]
edition = "2021"

name = "vsmtp-config"
version = "1.3.0-rc.1"
license = "GPL-3.0-only"

rust-version = "1.60"

authors = ["Team viridIT <https://viridit.com/>"]
description = "Next-gen MTA. Secured, Faster and Greener"

homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"
documentation = "https://docs.rs/crate/vsmtp-config/"

readme = "../../../README.md"
keywords = ["vsmtp"]
categories = ["data-structures"]

[package.metadata.release]
pre-release-replacements = [
  { file = "Cargo.toml", search = "vsmtp-common = \\{ path = \"../vsmtp-common\", version = .*", replace = "vsmtp-common = { path = \"../vsmtp-common\", version = \"{{version}}\" }", prerelease = true },
]

[dependencies]
vsmtp-common = { path = "../vsmtp-common", version = "1.3.0-rc.1" }

tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
tracing = "0.1.36"

users = { version = "0.11.0", features = [] }

serde = { version = "1.0.144", features = ["derive"] }
humantime-serde = "1.1.1"
strum = { version = "0.24.1", features = ["derive"] }

toml = "0.5.9"

rustls = { version = "0.20.6", features = ["tls12", "logging"] }
rustls-pemfile = "1.0.1"

rsa = "0.6.1"

hostname = "0.3.1"
trust-dns-resolver = { version = "0.21.2", default-features = false, features = [
  "system-config",
  "serde-config",
  "tokio-runtime",
] }

semver = { version = "1.0.13", features = ["serde"] }
serde_with = "2.0.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
vsmtp-test = { path = "../vsmtp-test" }
