[package]
edition = "2021"

name = "vsmtp-common"
version = "1.3.0-rc.1"
license = "GPL-3.0-only"

rust-version = "1.60"

authors = ["Team viridIT <https://viridit.com/>"]
description = "Next-gen MTA. Secured, Faster and Greener"

homepage = "https://github.com/viridIT/vSMTP"
repository = "https://github.com/viridIT/vSMTP"
documentation = "https://docs.rs/crate/vsmtp-common/"

readme = "../../../README.md"
keywords = ["vsmtp", "smtp", "mail"]
categories = ["data-structures"]

[dependencies]
vsmtp-auth = { path = "../vsmtp-auth", version = "1.3.0-rc.0" }
vsmtp-mail-parser = { path = "../vsmtp-mail-parser", version = "1.3.0-rc.0" }

# Re-exported
anyhow = "1.0.62"
log = { version = "0.4.17", features = ["serde"] }
serde_json = "1.0.85"
addr = { version = "0.15.4" }

strum = { version = "0.24.1", features = ["derive"] }
libc = "0.2.132"
lettre = { version = "0.10.0", default-features = false, features = [
    "smtp-transport",
    "builder",
    "tokio1-rustls-tls",
    "tracing",
    "pool",
] }
tokio = { version = "1.21.0", default-features = false, features = [
    "macros",
    "time",
    "sync",
    "fs",
    "net",
    "io-util",
    "rt-multi-thread",
] }
serde = { version = "1.0.144", features = ["derive"] }
serde_with = "2.0.0"

async-trait = "0.1.57"
either = { version = "1.8.0", features = ["serde"] }

base64 = "0.13.0"

[dev-dependencies]
users = { version = "0.11.0", features = [] }
pretty_assertions = "1.3.0"
vsmtp-mail-parser = { path = "../vsmtp-mail-parser" }
